### ISSUE TITLE
TinyChain panicking at runtime

### ISSUE THREAD

**Issue by manasrivastava** [haydnv/tinychain#19]
Platform:  MacOS 10.15.7

TinyChain Version: v0.2.3

Steps to reproduce:

- Create a workspace directory, in my case /tmp/tc.
> mkdir /tmp/tc

> tinychain --workspace /tmp/tc &

The process starts and serves requests on localhost:8702, however, the console returns a panic.

thread 'tokio-runtime-worker' panicked at 'range end index 2 out of range for slice of length 1', /Users/ms/.cargo/registry/src/github.com-1ecc6299db9ec823/tinychain-0.2.3/src/kernel/mod.rs:74:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**RUST_BACKTRACE=1:**

thread 'tokio-runtime-worker' panicked at 'range end index 2 out of range for slice of length 1', /Users/ms/.cargo/registry/src/github.com-1ecc6299db9ec823/tinychain-0.2.3/src/kernel/mod.rs:74:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/slice/index.rs:41:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: tinychain::http::server::HTTPServer::handle::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
   8: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
   9: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  10: tokio::runtime::task::harness::poll_future
  11: tokio::runtime::task::harness::Harness<T,S>::poll
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::thread_pool::worker::Context::run_task
  14: tokio::runtime::thread_pool::worker::Context::run
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
  16: tokio::runtime::thread_pool::worker::run
  17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  19: tokio::runtime::task::harness::Harness<T,S>::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**RUST_BACKTRACE=full:**
stack backtrace:
   0:        0x106fd9614 - std::backtrace_rs::backtrace::libunwind::trace::ha70d3c0580051b5e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x106fd9614 - std::backtrace_rs::backtrace::trace_unsynchronized::h70c3b3ef22cddd13
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x106fd9614 - std::sys_common::backtrace::_print_fmt::h698e42c1766250fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x106fd9614 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h18cc31b07c2f1a67
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x106ff5e1d - core::fmt::write::h24f8349e8e89c9af
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:        0x106fd28f6 - std::io::Write::write_fmt::hc54d7d6e95b15753
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:        0x106fdb949 - std::sys_common::backtrace::_print::h07ca439149358748
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x106fdb949 - std::sys_common::backtrace::print::hb7331bf9c4b208ca
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x106fdb949 - std::panicking::default_hook::{{closure}}::h11b550d560f5cc66
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:        0x106fdb4d9 - std::panicking::default_hook::he168e99d1cf91c3c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:        0x106fdbfcb - std::panicking::rust_panic_with_hook::hf87bfc4afef21ea6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:        0x106fdbaf5 - std::panicking::begin_panic_handler::{{closure}}::h19ac9cd24a19b238
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:        0x106fd9ab8 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fc3f41df3517232
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x106fdba5a - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:        0x10701df1b - std::panicking::begin_panic_fmt::h454a7382e425f0d5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
  15:        0x106880d45 - tinychain::main::{{closure}}::hbe4d6840b9b57c0c
  16:        0x1068c12cf - std::thread::local::LocalKey<T>::with::h93ece4e46390a1dc
  17:        0x1067ebe77 - tokio::runtime::enter::Enter::block_on::h1beea7376a8613f8
  18:        0x1068979d5 - tokio::runtime::thread_pool::ThreadPool::block_on::ha5455d5b0469e254
  19:        0x1068ce79d - tokio::runtime::Runtime::block_on::h0366da7e7d10745c
  20:        0x10689ff6e - tinychain::main::hd5ea5f8c1d104698
  21:        0x1068873ca - std::sys_common::backtrace::__rust_begin_short_backtrace::hf6700e5c8b346e35
  22:        0x1068873f1 - std::rt::lang_start::{{closure}}::h846c84964ec2cf5b
  23:        0x106fdc424 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0e377e204feaadc3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
  24:        0x106fdc424 - std::panicking::try::do_call::h9c5b8eda90bbe0b7
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  25:        0x106fdc424 - std::panicking::try::he150bdff9d5b30f2
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  26:        0x106fdc424 - std::panic::catch_unwind::h04e9c415c0907892
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  27:        0x106fdc424 - std::rt::lang_start_internal::h86f505dc7de50d93
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  28:        0x1068a0049 - _main

**Comment by haydnv** [comment]
Thanks for the bug report! This should be fixed in the next release (0.3.0 beta) but I will verify before closing this bug

**Comment by manasrivastava** [comment]
Thank you for the quick update!

**Comment by haydnv** [comment]
This is fixed in commit 764e8283
