### ISSUE TITLE
Add a graph visualizer tool

### ISSUE THREAD

**Issue by annzhukovets** [haydnv/tinychain#71]
Hi @haydnv! When debugging the tinychain code, we typically rely on the JSON representation of the execution graph. But it quickly becomes unreadable when working with moderately complex functions. Could you please think about adding a graph visualizer tool, same as TensorFlow has for example?
https://www.tensorflow.org/tensorboard/graphs
<img width="902" alt="Screenshot 2022-01-10 at 14 20 13" src="https://user-images.githubusercontent.com/22129384/148760655-6c9e76f6-3cb1-47cc-95b5-7863434e18cc.png">

**Comment by haydnv** [comment]
Here's a first draft: https://github.com/haydnv/tc-debug (you can see a usage example in tests/test_visualization.py). Let me know what improvements would be most helpful.

**Comment by haydnv** [comment]
I think this will be handled better using the WebAssembly client: #168 168
