### ISSUE TITLE
Possible bug in convXd.forward

### ISSUE THREAD

**Issue by mukahraman** [haydnv/tinychain#82]
Here, I am trying to evaluate the layer for 
`input_shape=[5,32], output_shape=[5,8], kernel_shape=[1], stride=1 `

which at forward throws
`tinychain.error.BadRequest: {'/error/bad_request': 'while resolving Tensor_7fd39c4f84c0: cannot broadcast into [5, 0, 32]: [5, 32]'}`

Padding seems to be the problem but I am not sure. It works for `stride=2 `.

```
    def test1D(self):
        data = np.linspace(1, 2, 160).reshape(5, 32)
        self.execute(data, data, self.conv_1d)

    def execute(self, inputs, labels, conv):
        cxt = tc.Context()
        cxt.inputs = tc.tensor.Dense.load(inputs.shape, tc.F32, inputs.flatten().tolist())
        cxt.layer = conv(inputs.shape, [5, 8], [1], 1)
        cxt.result = cxt.layer.forward(cxt.inputs)

        response = self.host.post(ENDPOINT, cxt)
        print(response)
```

**Comment by haydnv** [comment]
This should have been fixed by #81 but please reopen if you continue to experience this issue
